envmon2/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('', include('stats.urls')),
]

stats/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
]

stats/models.py
from django.db import models
from django.utils import timezone



class Stats(models.Model):
    created = models.DateTimeField(default=timezone.now)
    temperature = models.DecimalField(max_digits=5, decimal_places=2)
    humidity = models.DecimalField(max_digits=5, decimal_places=2)
    pressure = models.DecimalField(max_digits=5, decimal_places=2)
    outside_temp = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return '{} -- Temp: {}, Humidity: {}, Pressure: {}'.format(
            self.created,
            self.temperature,
            self.humidity,
            self.pressure,
        )    

stats/forms.py
from django import forms


class statsSearchForm(forms.Form):
    start_date = forms.DateTimeField()
    end_date = forms.DateTimeField()


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

stats/views.py
from datetime import datetime, timedelta
import pytz

from django.contrib import messages
from django.shortcuts import render
from django.utils import timezone
from django.views.generic import FormView

from . import forms, models



class Index(FormView):
    template_name = 'stats/index.html'
    form_class = forms.statsSearchForm

    def get_initial(self):
        init = super().get_initial()
        init.update({
            'start_date':self.request.GET.get('start_date'),
            'end_date':self.request.GET.get('end_date'),
        })
        return init

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        now = datetime.now()
        day_ago = now - timedelta(days=1)

        try:
            start_date = self.request.GET.get('start_date')
            if start_date:
                start_date = datetime.strptime(start_date, '%m/%d/%Y %I:%M %p')
            else:
                start_date = day_ago
        except Exception as e:
            messages.warning(self.request, 'Invalid start date selected')
            start_date = day_ago

        try:
            end_date = self.request.GET.get('end_date')
            if end_date:
                end_date = datetime.strptime(end_date, '%m/%d/%Y %I:%M %p')
            else:
                end_date = now
        except Exception as e:
            messages.warning(self.request, 'Invalid end date selected')
            end_date = now

        start_date = start_date.astimezone(pytz.UTC)
        end_date = end_date.astimezone(pytz.UTC)

        stats = models.Stats.objects.filter(
            created__gte=start_date,
            created__lte=end_date,
        ).values_list(
            'created',
            'temperature',
            'humidity',
            'pressure',
            'outside_temp',
            named=True
        ).order_by('created')
        dates = [stat.created.astimezone(timezone.get_current_timezone()).strftime('%Y-%m-%d %I:%M %p') for stat in stats]
        temps = [stat.temperature.to_eng_string() for stat in stats]
        hums = [stat.humidity.to_eng_string() for stat in stats]
        press = [stat.pressure.to_eng_string() for stat in stats]
        ext_temps = [stat.outside_temp.to_eng_string() for stat in stats]

        current = models.Stats.objects.latest('created')

        context.update({
            'full_stats': stats,
            'curr_temp': current.temperature,
            'curr_humidity': current.humidity,
            'curr_pressure': current.pressure,
            'curr_outside_temp': current.outside_temp,
            'labels': dates,
            'temp_chart_data': temps,
            'humidity_chart_data': hums,
            'pressure_chart_data': press,
            'outside_temp_chart_data': ext_temps,
        })

        return context

stats/templates/stats/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <title>Fairbanks OIT Hallway Weather</title>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/js/solid.min.js" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/js/fontawesome.min.js" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/js/bootstrap.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@eonasdan/tempus-dominus@6.7.7/dist/js/tempus-dominus.min.js" crossorigin="anonymous"></script>

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@eonasdan/tempus-dominus@6.7.7/dist/css/tempus-dominus.min.css" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/css/bootstrap.min.css">

  <style>
    .graph-content {
      margin-left: 10%;
      margin-right: 10%;
      margin-top: 10px;
    }

    .curr-stat {
      font-size: 36px;
      text-align: center;
      vertical-align: middle;
      color: lightgrey;
    }

    .curr-meas {
      font-size: 22px;
      vertical-align: unset;
      color: lightgrey;
    }

    .curr-lbl {
      font-weight: 600;
      color: black;
      line-height: 4px;
    }

    form {
      display: flex;
      justify-content: center;
      align-items: center;
      border: none;
      margin-bottom: 30px;
    }

    .stat-bar {
      display: flex;
      text-align: center;
      justify-content: center;
      align-items: center;
      background-color: slategray;
    }

    .stat-img {
      height: 80px;
      padding: 10px;
    }

  </style>
</head>
  
<body class="container-fluid">
  <div class="content">
    <center class="row" style="background-color: powderblue; padding-top: 10px;">
      <h5>Fairbanks OIT Hallway Weather</h5>
			<div class="text-end" style="margin-top: -33px;">
				<input type="checkbox" id="auto_refresh" name="auto_refresh" value="false">
				<label for="auto_refresh">Auto-refresh (5min)</label>
			</div>
    </center>
    <div class="row stat-bar">
      <div class="col-md-3">
        <img class="stat-img" src="{% static 'img/icon-temp.svg' %}" alt="Thermometer Image">
        <span class="curr-stat">{{ curr_temp }}</span>
        <span class="curr-meas">&#176;F</span>
      </div>
      <div class="col-md-3">
        <img class="stat-img" src="{% static '/img/icon-humidity.svg' %}" alt="Humidity Image">
        <span class="curr-stat">{{ curr_humidity }}</span>
        <span class="curr-meas">%</span>
      </div>
      <div class="col-md-3">
        <img class="stat-img" src="{% static 'img/icon-pressure.svg' %}" alt="Barometric Pressure Image">
        <span class="curr-stat">{{ curr_pressure }}</span>
        <span class="curr-meas">inHg</span>
      </div>
    </div>
  </div>
  <div class="row">
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }}">{{ message }}</div>
    {% endfor %}
  </div>
  </div>
	<div class="graph-content">
    <form class="row gy-2 gx-3 align-items-center" method="GET" action="/"> <div class="col-sm-3"></div>
      <div class="col-sm-3">
        <label for="id_start_date" class="form-label">Start Date/Time</label>
        <div class="input-group" id="start_date_grp" placeholder="Start Date/Time"
          data-td-target-input="nearest" data-td-target-toggle="nearest">
          {{ form.start_date }}
          <span class="input-group-text" data-td-target="#id_start_date" data-td-toggle="datetimepicker">
            <span class="fa-solid fa-calendar"></span>
          </span>
        </div>
      </div>
      <div class="col-sm-3">
        <label for="id_end_date" class="form-label">End Date/Time</label>
        <div class="input-group" id="end_date_grp" data-td-target-input="nearest" data-td-target-toggle="nearest">
          {{ form.end_date }}
          <span class="input-group-text" data-td-target="#id_end_date" data-td-toggle="datetimepicker">
            <span class="fa-solid fa-calendar"></span>
          </span>
        </div>
      </div>
      <div class="col-sm-3">
        <input type="submit" class="btn btn-primary" style="margin-bottom: -25px;" value="Go"></input>
      </div>
    </form>

    <div class="row" style="display: flex; justify-content: center; align-items: center;">
      <div class="col-md-10">
        <canvas id="stats_graph"></canvas>
      </div>
    </div>
  </div>

  <script>
    let refreshTimeout;

		// set up datepickers
    new tempusDominus.TempusDominus(document.getElementById('id_start_date'));
    new tempusDominus.TempusDominus(document.getElementById('id_end_date'));


    function setRefreshQS(is_checked) {
      const url = new URL(location);
      url.searchParams.set("auto_refresh", is_checked);
      history.pushState({}, "", url);
    }
    
    function setRefreshTimeout() {
      refreshTimeout = window.setTimeout( function() {
        window.location.reload();
      }, 300000); 
    }

    function clearRefreshTimeout() {
      clearTimeout(refreshTimeout);
    }

		// auto refresh page when checked
		const refreshChkBox = document.getElementById('auto_refresh');
    const params = new Proxy(new URLSearchParams(window.location.search), {
      get: (searchParams, prop) => searchParams.get(prop),
    });

    if (params.auto_refresh === 'true') {
      refreshChkBox.checked = true;
      setRefreshTimeout();
    }

		refreshChkBox.addEventListener('change', e => {
			if(e.target.checked === true) {
        setRefreshQS(true);
        setRefreshTimeout();
      }
			if(e.target.checked === false) {
        setRefreshQS(false);
				clearRefreshTimeout();
			}
		});

    ctx = document.getElementById('stats_graph');
    new Chart(ctx, {
      type: 'line',
      data: {
        labels: {{ labels|safe }},
        datasets: [{
          label: 'Pressure',
          backgroundColor: '#00a10596',
          borderColor: '#006003',
          fill: false,
          tension: .3,
          pointStyle: false,
          data: {{ pressure_chart_data|safe }},
        }, {
          label: 'Humidity',
          backgroundColor: '#2196f39e',
          borderColor: '#0074d1',
          fill: false,
          tension: .3,
          pointStyle: false,
          data: {{ humidity_chart_data|safe }},
        }, {
          label: 'Temperature',
          backgroundColor: '#b76d7e7a',
          borderColor: '#971111',
          fill: false,
          tension: .3,
          pointStyle: false,
          data: {{ temp_chart_data|safe }},
        }, {
          label: 'Outside Temp',
          backgroundColor: '#607d8b7a',
          borderColor: '#607d8b',
          fill: false,
          tension: .3,
          pointStyle: false,
          data: {{ outside_temp_chart_data|safe }},
        }]
      },
      options: {
        scales: {
          x: { 
            //type: 'time',
            ticks: {
                autoSkip: true,
                maxTicksLimit: 20 
            }
          }
        }
      },
             
      responsive: true
    });
  </script>
</body>
</html>